// Code generated by goctl. DO NOT EDIT.
package types

type ConvertRequset struct {
	LongUrl string `json:"longUrl" validate:"required"`
}

type ConvertResponse struct {
	ShortUrl string `json:"shortUrl"`
}

type ShowRequset struct {
	ShortUrl string `path:"shortUrl" validate:"required"`
}

type ShowResponse struct {
	LongUrl string `json:"longUrl"`
}
